# frozen_string_literal: true

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command("node", ["-p", "require.resolve('react-native/scripts/react_native_pods.rb',{paths: [process.argv[1]]},)", __dir__]).strip

platform :ios, "16.0"
prepare_react_native_project!

linkage = ENV.fetch("USE_FRAMEWORKS", nil)
unless linkage.nil?
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! linkage: linkage.to_sym
end

target "Catalog" do
  config = use_native_modules!
  host_cpu = RbConfig::CONFIG["host_cpu"]

  # Flags change depending on the env values.
  flags = get_default_flags

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: flags[:hermes_enabled],
    fabric_enabled: flags[:fabric_enabled],
    # An absolute path to your application root.
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  # PSPDFKit iOS SDK version specified by PSPDFKit React Native Plugin. Do not remove this line.
  # Instant iOS SDK version specified by PSPDFKit React Native Plugin. Do not remove this line.

  target "CatalogTests" do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |target_config|
          if host_cpu.eql?("x86_64")
            target_config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
          target_config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.0"
        end
      end
      aggregate_target.user_project.save
    end
    installer.pods_project.build_configurations.each do |excl_config|
      if host_cpu.eql?("x86_64")
        excl_config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
      excl_config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.0"
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |target_config|
        target_config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.0"
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      mac_catalyst_enabled: false
    )
  end
end
